// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXHCwDOCqTGTKseBw_ZjsjeUHpdqzUyFE',
    appId: '1:618114489705:android:908fad72b3a499a16971f8',
    messagingSenderId: '618114489705',
    projectId: 'mygame-233d5',
    storageBucket: 'mygame-233d5.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARVWGLfF2OQ3eBfCl9Q_tfnyoqeywINho',
    appId: '1:618114489705:ios:9b23886f10407fa06971f8',
    messagingSenderId: '618114489705',
    projectId: 'mygame-233d5',
    storageBucket: 'mygame-233d5.appspot.com',
    androidClientId: '618114489705-7lbagttg2bm1aepbsars2mqhoqmt08ac.apps.googleusercontent.com',
    iosClientId: '618114489705-68kbl30d15etjbl8upmh4b0oqkag2uku.apps.googleusercontent.com',
    iosBundleId: 'com.mb.mygame.RunnerTests',
  );
}
